// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/goplus/dql/colly"

const _ = true

type kling struct {
	colly.Site
	*App
}
type App struct {
	colly.App
}
//line demo/kling/main_colly.gox:1
func (this *App) MainEntry() {
//line demo/kling/main_colly.gox:1:1
	this.CacheDir("../../.env/data/kling")
}
func (this *App) Main() {
	_xgo_obj0 := &kling{App: this}
	colly.XGot_App_Main(this, _xgo_obj0)
}
//line demo/kling/kling_site.gox:1
// headlessWaitReady "document"
func (this *kling) Main() {
//line demo/kling/kling_site.gox:2:1
	this.Start("https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview")
}
func main() {
	new(App).Main()
}
